### ISSUE TITLE
Upgrade to newer Flink version

### ISSUE THREAD

**Issue by rmetzger** [isopropylcyanide/flink-couchbase-data-starter#1]
A user on the flink mailing list mentioned this repo, asking for a higher version.

**Comment by isopropylcyanide** [comment]
Hi @rmetzger Can you point me to the mailing list? What version are we looking for?

**Comment by rmetzger** [comment]
This is the thread: https://lists.apache.org/thread.html/r7a7e8a7f8b33141f0c31bfe3508335b0bb422408312c5eb3834b963f%40%3Cuser.flink.apache.org%3E
