### ISSUE TITLE
Submit repository to flink-packages.org

### ISSUE THREAD

**Issue by rmetzger** [isopropylcyanide/flink-couchbase-data-starter#2]
The Flink community launched flink-packages.org in order to increase visibility for community projects.

**Comment by isopropylcyanide** [comment]
I really appreciate this suggestion @rmetzger However, the repository is lacking docs and proper class design. I doubt it would provides enough functionality to warrant a submission to the flink-packages.org

**Comment by rmetzger** [comment]
I think that's fine. flink-packages.org is a community-run site. People need to decide themselves if they consider a project stable enough or not.

By making this repository more public, it is also more likely that you get contributions fixing the issues you mentioned.

**Comment by isopropylcyanide** [comment]
Noted. I'll prioritise it. Thank you.

**Comment by isopropylcyanide** [comment]
Package raised: https://flink-packages.org/packages/flink-couchbase-sink @rmetzger

**Comment by rmetzger** [comment]
Thanks a lot :)
